info:
  name: Get Deployment
  type: http
  seq: 3

http:
  method: GET
  url: "{{ENDPOINT}}/v1alpha1/inference/deployments/{{DEPLOYMENT_ID}}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
